# Build the container image (Viewer)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/$_IMAGE_NAME:$BRANCH_NAME', '.']
    waitFor: ['-']
    id: 'build'

# Push the container image to Container Registry (viewer)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/$_IMAGE_NAME:$BRANCH_NAME']
    waitFor: ['build']
    id: 'push'