steps:
# Build the container image 
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/$_IMAGE_NAME:latest', '.']
    waitFor: ['-']
    timeout: 3600s
    id: 'build'

# Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/$_IMAGE_NAME:latest']
    waitFor: ['build']
    id: 'push'
    
timeout: 3600s